language: ruby

rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - jruby-9.1
  - jruby-9.2

sudo: false

script: bundle exec rake test

bundler_args: --without docs release repl
