version: 0.2

phases:
    install:
      commands:
        - gem install bundler
        - bundler install
    pre_build:
      commands:
        - DATABASE_URL=$DATABASE_URL RAILS_ENV=$RAILS_ENV bundle exec rake db:migrate
